version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #volumes:
    #  - ./api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    #volumes:
    #  - ./app:/var/www/html
    ports:
      - "3000:3000"