version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #volumes:
    #  - ./api:/var/www/html
    ports:
      - "8080:80"
  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    #volumes:
    #  - ./app:/var/www/html
    ports:
      - "5000:5000"
